#!/usr/bin/env lua

package.cpath = package.cpath .. ";/Users/scawful/.local/share/sketchybar_lua/?.so"
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/sketchybar/helpers/lib/?.lua"

package.loaded["main"] = nil
require("main")
