name: Scripts Quality

on:
  push:
  pull_request:

jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - name: Run Script Checks
        run: |
          chmod +x scripts/check_scripts.sh
          scripts/check_scripts.sh --ci
